# Generated by Django 2.2.16 on 2020-09-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('email', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('mdp', models.CharField(max_length=255)),
            ],
        ),
    ]
