# Generated by Django 2.2.16 on 2020-09-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('nomProduit', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
